"""Add trip validity and notifications with nullable start_time

Revision ID: 0d2b276fd120
Revises: 88eb1c0992d9
Create Date: 2025-05-01 09:07:07.674983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2b276fd120'
down_revision = '88eb1c0992d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
